version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    depends_on:
      - db
    volumes:
      - .:/www/public

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: spikk
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: spikk_admin
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
