version: '3.9'
services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - $PORT:$PORT
    networks:
      - db
    env_file:
      - ./.env
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - BASE_URL=$BASE_URL
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_HOST=db
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRATION_TIME=$JWT_EXPIRATION_TIME
      - MONNIFY_BASE_URL=$MONNIFY_BASE_URL
      - MONNIFY_SECRET_KEY= $MONNIFY_SECRET_KEY
      - MONNIFY_API_KEY=$MONNIFY_API_KEY
      - MONNIFY_CONTRACT_CODE=$MONNIFY_CONTRACT_CODE
      - MONNIFY_ACCOUNT_NO=$MONNIFY_ACCOUNT_NO
      - CLIENT_BASE_URL=$CLIENT_BASE_URL
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    depends_on:
      - db
    volumes:
      - .:/www/public

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: spikk
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: spikk_admin
    ports:
      - 3306:3306
    networks:
      - db
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql:
networks:
  db:
    driver: bridge
