name: Spikk Deploy 
on: 
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Spikk
    steps:  
      - name: Checkout files
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kastroud/spikk-web-backend
  
  deploy:
    needs : build
    runs-on : ubuntu-latest
    environment : Spikk
    steps:
      - name: Checkout files
        uses: actions/checkout@v2 

      - name: Get tag name
        uses: olegtarasov/get-tag@v2
      
      - name: setup  git on server
        run: |
              apt-get update -qq \
              apt-get install -qq git \
              'which ssh-agent || ( apt-get install -qq openssh-client )' \
              eval $(ssh-agent -s) \
              ssh-add <(echo "${{secrets.DOCKERHUB_TOKEN}}") \
              mkdir -p ~/.ssh \
              '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

      - name: mkdir
        run: ssh ${{ secrets.DIGITALOCEAN_USERNAME}}@${{secrets.DIGITALOCEAN_URL}} "mkdir test"
  