name: Spikk Deploy 
on: 
  push:
    branches:
      - "master"
jobs:  
  deploy:
    runs-on : self-hosted
    environment : Spikk
    steps:
      - name: Checkout files
        uses: actions/checkout@v2 
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: run docker 
        run : docker-compose up -d
  