name: Spikk Deploy 
on: 
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout files
        uses: actions/checkout@v2
      
      - name:  Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          email: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: kastroud/spikk-web-app-backend
          tag_with_ref: true
          tag_with_sha: true
  